
package finalproject;

import javax.swing.JOptionPane;


public class home extends javax.swing.JFrame {


    public home() 
    {
          setUndecorated(true);
          setBounds(300,100,300,400);
      
        initComponents();
        setSize(723,510);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Jl0 = new javax.swing.JLabel();
        Jb1 = new javax.swing.JButton();
        Jb3 = new javax.swing.JButton();
        Jb4 = new javax.swing.JButton();
        Jl1 = new javax.swing.JLabel();
        Jb5 = new javax.swing.JButton();
        Jl2 = new javax.swing.JLabel();
        Jb6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Jl0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jl0.setText("          HOME");
        getContentPane().add(Jl0);
        Jl0.setBounds(30, 30, 171, 31);

        Jb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jb1.setText("ADMIN/STUDENT/TEACHER");
        Jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jb1);
        Jb1.setBounds(60, 100, 290, 40);

        Jb3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jb3.setText("LOGIN");
        Jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb3ActionPerformed(evt);
            }
        });
        getContentPane().add(Jb3);
        Jb3.setBounds(420, 100, 93, 41);

        Jb4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jb4.setText("       ADD/MODIFY ->");
        Jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb4ActionPerformed(evt);
            }
        });
        getContentPane().add(Jb4);
        Jb4.setBounds(55, 202, 223, 44);

        Jl1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Jl1.setText("TEACHER");
        getContentPane().add(Jl1);
        Jl1.setBounds(324, 202, 179, 44);

        Jb5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jb5.setText("        ADD/MODIFY->");
        Jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb5ActionPerformed(evt);
            }
        });
        getContentPane().add(Jb5);
        Jb5.setBounds(55, 264, 223, 42);

        Jl2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Jl2.setText("STUDENT");
        getContentPane().add(Jl2);
        Jl2.setBounds(324, 264, 179, 42);

        Jb6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jb6.setText("ALLOTEMENT FOR ->");
        Jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb6ActionPerformed(evt);
            }
        });
        getContentPane().add(Jb6);
        Jb6.setBounds(55, 394, 223, 41);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("STUDENTS ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(324, 391, 137, 41);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(668, 0, 55, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("ALLOTEMENT FOR ->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(55, 333, 223, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("TEACHERS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(324, 334, 137, 36);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/image[home3].jpg"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 720, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb4ActionPerformed
       new teacherframe().setVisible(true);
       dispose();
    }//GEN-LAST:event_Jb4ActionPerformed

    private void Jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb3ActionPerformed
    new admin().setVisible(true);
    dispose();
    }//GEN-LAST:event_Jb3ActionPerformed

    private void Jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb5ActionPerformed
       new student().setVisible(true);
       dispose();
    }//GEN-LAST:event_Jb5ActionPerformed

    private void Jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb6ActionPerformed
    new addroom().setVisible(true);
    dispose();
    }//GEN-LAST:event_Jb6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int x=JOptionPane.showConfirmDialog(this, "DO YOU WANT TO EXIT ??", "Confirmation", JOptionPane.YES_NO_OPTION);
         if(x==JOptionPane.YES_OPTION)
         {System.exit(0);} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new allot_teacher().setVisible(true);
      dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void Jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb1ActionPerformed
            new admin_or_student().setVisible(true);
      dispose();
  // TODO add your handling code here:
    }//GEN-LAST:event_Jb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jb1;
    private javax.swing.JButton Jb3;
    private javax.swing.JButton Jb4;
    private javax.swing.JButton Jb5;
    private javax.swing.JButton Jb6;
    private javax.swing.JLabel Jl0;
    private javax.swing.JLabel Jl1;
    private javax.swing.JLabel Jl2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
